name: gh-pages

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Install WASM tools
      run: dotnet workload install wasm-tools
    - name: Install dotnet tools
      run: dotnet tool restore
      working-directory: src
    - name: Paket install
      run: dotnet paket install
      working-directory: src
    - name: Publish with dotnet
      run: dotnet publish --configuration Release --output build src/web/GraphExplorer.Client.fsproj
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build
        branch: gh-pages
        clean: true